app:
  jwt:
    secret: "${JWT_SECRET}"

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tsms
    username: bar
    password: bar
  
  flyway:
    url: jdbc:postgresql://localhost:5432/tsms
    user: bar
    password: bar
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    org.flywaydb: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info